#!/bin/bash
tag=$1
dest_dir="PreselectedWithRegression"

cd ${dest_dir}${tag}
mv Histograms_Preselected_GluGluToRadionToHHTo4B_M-260_narrow_13TeV-madgraph.root Histograms_Preselected_GluGluToBulkGravitonToHHTo4B_M-260_narrow_13TeV-madgraph.root  
mv Histograms_Preselected_GluGluToRadionToHHTo4B_M-270_narrow_13TeV-madgraph.root Histograms_Preselected_GluGluToBulkGravitonToHHTo4B_M-270_narrow_13TeV-madgraph.root  
mv Histograms_Preselected_GluGluToRadionToHHTo4B_M-300_narrow_13TeV-madgraph.root Histograms_Preselected_GluGluToBulkGravitonToHHTo4B_M-300_narrow_13TeV-madgraph.root  
mv Histograms_Preselected_GluGluToRadionToHHTo4B_M-350_narrow_13TeV-madgraph.root Histograms_Preselected_GluGluToBulkGravitonToHHTo4B_M-350_narrow_13TeV-madgraph.root  
mv Histograms_Preselected_GluGluToRadionToHHTo4B_M-400_narrow_13TeV-madgraph.root Histograms_Preselected_GluGluToBulkGravitonToHHTo4B_M-400_narrow_13TeV-madgraph.root  
mv Histograms_Preselected_GluGluToRadionToHHTo4B_M-450_narrow_13TeV-madgraph.root Histograms_Preselected_GluGluToBulkGravitonToHHTo4B_M-450_narrow_13TeV-madgraph.root  
mv Histograms_Preselected_GluGluToRadionToHHTo4B_M-500_narrow_13TeV-madgraph.root Histograms_Preselected_GluGluToBulkGravitonToHHTo4B_M-500_narrow_13TeV-madgraph.root  
mv Histograms_Preselected_GluGluToRadionToHHTo4B_M-550_narrow_13TeV-madgraph.root Histograms_Preselected_GluGluToBulkGravitonToHHTo4B_M-550_narrow_13TeV-madgraph.root  
mv Histograms_Preselected_GluGluToRadionToHHTo4B_M-600_narrow_13TeV-madgraph.root Histograms_Preselected_GluGluToBulkGravitonToHHTo4B_M-600_narrow_13TeV-madgraph.root  
mv Histograms_Preselected_GluGluToRadionToHHTo4B_M-650_narrow_13TeV-madgraph.root Histograms_Preselected_GluGluToBulkGravitonToHHTo4B_M-650_narrow_13TeV-madgraph.root  
mv Histograms_Preselected_GluGluToRadionToHHTo4B_M-750_narrow_13TeV-madgraph.root Histograms_Preselected_GluGluToBulkGravitonToHHTo4B_M-750_narrow_13TeV-madgraph.root  
mv Histograms_Preselected_GluGluToRadionToHHTo4B_M-800_narrow_13TeV-madgraph.root Histograms_Preselected_GluGluToBulkGravitonToHHTo4B_M-800_narrow_13TeV-madgraph.root  
mv Histograms_Preselected_GluGluToRadionToHHTo4B_M-900_narrow_13TeV-madgraph.root Histograms_Preselected_GluGluToBulkGravitonToHHTo4B_M-900_narrow_13TeV-madgraph.root 
mv Histograms_Preselected_RadionTohhTohbbhbb_narrow_M-1000_13TeV-madgraph.root Histograms_Preselected_BulkGravTohhTohbbhbb_narrow_M-1000_13TeV-madgraph.root
mv Histograms_Preselected_RadionTohhTohbbhbb_narrow_M-1200_13TeV-madgraph.root Histograms_Preselected_BulkGravTohhTohbbhbb_narrow_M-1200_13TeV-madgraph.root
mv PreSelected_GluGluToRadionToHHTo4B_M-260_narrow_13TeV-madgraph.root PreSelected_GluGluToBulkGravitonToHHTo4B_M-260_narrow_13TeV-madgraph.root  
mv PreSelected_GluGluToRadionToHHTo4B_M-270_narrow_13TeV-madgraph.root PreSelected_GluGluToBulkGravitonToHHTo4B_M-270_narrow_13TeV-madgraph.root  
mv PreSelected_GluGluToRadionToHHTo4B_M-300_narrow_13TeV-madgraph.root PreSelected_GluGluToBulkGravitonToHHTo4B_M-300_narrow_13TeV-madgraph.root  
mv PreSelected_GluGluToRadionToHHTo4B_M-350_narrow_13TeV-madgraph.root PreSelected_GluGluToBulkGravitonToHHTo4B_M-350_narrow_13TeV-madgraph.root  
mv PreSelected_GluGluToRadionToHHTo4B_M-400_narrow_13TeV-madgraph.root PreSelected_GluGluToBulkGravitonToHHTo4B_M-400_narrow_13TeV-madgraph.root  
mv PreSelected_GluGluToRadionToHHTo4B_M-450_narrow_13TeV-madgraph.root PreSelected_GluGluToBulkGravitonToHHTo4B_M-450_narrow_13TeV-madgraph.root  
mv PreSelected_GluGluToRadionToHHTo4B_M-500_narrow_13TeV-madgraph.root PreSelected_GluGluToBulkGravitonToHHTo4B_M-500_narrow_13TeV-madgraph.root  
mv PreSelected_GluGluToRadionToHHTo4B_M-550_narrow_13TeV-madgraph.root PreSelected_GluGluToBulkGravitonToHHTo4B_M-550_narrow_13TeV-madgraph.root  
mv PreSelected_GluGluToRadionToHHTo4B_M-600_narrow_13TeV-madgraph.root PreSelected_GluGluToBulkGravitonToHHTo4B_M-600_narrow_13TeV-madgraph.root  
mv PreSelected_GluGluToRadionToHHTo4B_M-650_narrow_13TeV-madgraph.root PreSelected_GluGluToBulkGravitonToHHTo4B_M-650_narrow_13TeV-madgraph.root  
mv PreSelected_GluGluToRadionToHHTo4B_M-750_narrow_13TeV-madgraph.root PreSelected_GluGluToBulkGravitonToHHTo4B_M-750_narrow_13TeV-madgraph.root  
mv PreSelected_GluGluToRadionToHHTo4B_M-800_narrow_13TeV-madgraph.root PreSelected_GluGluToBulkGravitonToHHTo4B_M-800_narrow_13TeV-madgraph.root  
mv PreSelected_GluGluToRadionToHHTo4B_M-900_narrow_13TeV-madgraph.root PreSelected_GluGluToBulkGravitonToHHTo4B_M-900_narrow_13TeV-madgraph.root 
mv PreSelected_RadionTohhTohbbhbb_narrow_M-1000_13TeV-madgraph.root  PreSelected_BulkGravTohhTohbbhbb_narrow_M-1000_13TeV-madgraph.root
mv PreSelected_RadionTohhTohbbhbb_narrow_M-1200_13TeV-madgraph.root  PreSelected_BulkGravTohhTohbbhbb_narrow_M-1200_13TeV-madgraph.root
cd LMRSelection_chi2
mv Histograms_LMR_GluGluToRadionToHHTo4B_M-260_narrow_13TeV-madgraph.root Histograms_LMR_GluGluToBulkGravitonToHHTo4B_M-260_narrow_13TeV-madgraph.root
mv Histograms_LMR_GluGluToRadionToHHTo4B_M-270_narrow_13TeV-madgraph.root Histograms_LMR_GluGluToBulkGravitonToHHTo4B_M-270_narrow_13TeV-madgraph.root
mv Histograms_LMR_GluGluToRadionToHHTo4B_M-300_narrow_13TeV-madgraph.root Histograms_LMR_GluGluToBulkGravitonToHHTo4B_M-300_narrow_13TeV-madgraph.root
mv Histograms_LMR_GluGluToRadionToHHTo4B_M-350_narrow_13TeV-madgraph.root Histograms_LMR_GluGluToBulkGravitonToHHTo4B_M-350_narrow_13TeV-madgraph.root
mv Histograms_LMR_GluGluToRadionToHHTo4B_M-400_narrow_13TeV-madgraph.root Histograms_LMR_GluGluToBulkGravitonToHHTo4B_M-400_narrow_13TeV-madgraph.root
mv Histograms_LMR_GluGluToRadionToHHTo4B_M-450_narrow_13TeV-madgraph.root Histograms_LMR_GluGluToBulkGravitonToHHTo4B_M-450_narrow_13TeV-madgraph.root
mv Histograms_LMR_GluGluToRadionToHHTo4B_M-500_narrow_13TeV-madgraph.root Histograms_LMR_GluGluToBulkGravitonToHHTo4B_M-500_narrow_13TeV-madgraph.root
mv Histograms_LMR_GluGluToRadionToHHTo4B_M-550_narrow_13TeV-madgraph.root Histograms_LMR_GluGluToBulkGravitonToHHTo4B_M-550_narrow_13TeV-madgraph.root
mv Histograms_LMR_GluGluToRadionToHHTo4B_M-600_narrow_13TeV-madgraph.root Histograms_LMR_GluGluToBulkGravitonToHHTo4B_M-600_narrow_13TeV-madgraph.root
mv Histograms_LMR_GluGluToRadionToHHTo4B_M-650_narrow_13TeV-madgraph.root Histograms_LMR_GluGluToBulkGravitonToHHTo4B_M-650_narrow_13TeV-madgraph.root
mv Histograms_LMR_GluGluToRadionToHHTo4B_M-750_narrow_13TeV-madgraph.root Histograms_LMR_GluGluToBulkGravitonToHHTo4B_M-750_narrow_13TeV-madgraph.root
mv Histograms_LMR_GluGluToRadionToHHTo4B_M-800_narrow_13TeV-madgraph.root Histograms_LMR_GluGluToBulkGravitonToHHTo4B_M-800_narrow_13TeV-madgraph.root
mv Histograms_LMR_GluGluToRadionToHHTo4B_M-900_narrow_13TeV-madgraph.root Histograms_LMR_GluGluToBulkGravitonToHHTo4B_M-900_narrow_13TeV-madgraph.root
mv Histograms_LMR_RadionTohhTohbbhbb_narrow_M-1000_13TeV-madgraph.root Histograms_LMR_BulkGravTohhTohbbhbb_narrow_M-1000_13TeV-madgraph.root
mv Histograms_LMR_RadionTohhTohbbhbb_narrow_M-1200_13TeV-madgraph.root Histograms_LMR_BulkGravTohhTohbbhbb_narrow_M-1200_13TeV-madgraph.root
cd ..
cd MMRSelection_chi2
mv Histograms_MMR_GluGluToRadionToHHTo4B_M-260_narrow_13TeV-madgraph.root Histograms_MMR_GluGluToBulkGravitonToHHTo4B_M-260_narrow_13TeV-madgraph.root
mv Histograms_MMR_GluGluToRadionToHHTo4B_M-270_narrow_13TeV-madgraph.root Histograms_MMR_GluGluToBulkGravitonToHHTo4B_M-270_narrow_13TeV-madgraph.root
mv Histograms_MMR_GluGluToRadionToHHTo4B_M-300_narrow_13TeV-madgraph.root Histograms_MMR_GluGluToBulkGravitonToHHTo4B_M-300_narrow_13TeV-madgraph.root
mv Histograms_MMR_GluGluToRadionToHHTo4B_M-350_narrow_13TeV-madgraph.root Histograms_MMR_GluGluToBulkGravitonToHHTo4B_M-350_narrow_13TeV-madgraph.root
mv Histograms_MMR_GluGluToRadionToHHTo4B_M-400_narrow_13TeV-madgraph.root Histograms_MMR_GluGluToBulkGravitonToHHTo4B_M-400_narrow_13TeV-madgraph.root
mv Histograms_MMR_GluGluToRadionToHHTo4B_M-450_narrow_13TeV-madgraph.root Histograms_MMR_GluGluToBulkGravitonToHHTo4B_M-450_narrow_13TeV-madgraph.root
mv Histograms_MMR_GluGluToRadionToHHTo4B_M-500_narrow_13TeV-madgraph.root Histograms_MMR_GluGluToBulkGravitonToHHTo4B_M-500_narrow_13TeV-madgraph.root
mv Histograms_MMR_GluGluToRadionToHHTo4B_M-550_narrow_13TeV-madgraph.root Histograms_MMR_GluGluToBulkGravitonToHHTo4B_M-550_narrow_13TeV-madgraph.root
mv Histograms_MMR_GluGluToRadionToHHTo4B_M-600_narrow_13TeV-madgraph.root Histograms_MMR_GluGluToBulkGravitonToHHTo4B_M-600_narrow_13TeV-madgraph.root
mv Histograms_MMR_GluGluToRadionToHHTo4B_M-650_narrow_13TeV-madgraph.root Histograms_MMR_GluGluToBulkGravitonToHHTo4B_M-650_narrow_13TeV-madgraph.root
mv Histograms_MMR_GluGluToRadionToHHTo4B_M-750_narrow_13TeV-madgraph.root Histograms_MMR_GluGluToBulkGravitonToHHTo4B_M-750_narrow_13TeV-madgraph.root
mv Histograms_MMR_GluGluToRadionToHHTo4B_M-800_narrow_13TeV-madgraph.root Histograms_MMR_GluGluToBulkGravitonToHHTo4B_M-800_narrow_13TeV-madgraph.root
mv Histograms_MMR_GluGluToRadionToHHTo4B_M-900_narrow_13TeV-madgraph.root Histograms_MMR_GluGluToBulkGravitonToHHTo4B_M-900_narrow_13TeV-madgraph.root
mv Histograms_MMR_RadionTohhTohbbhbb_narrow_M-1000_13TeV-madgraph.root Histograms_MMR_BulkGravTohhTohbbhbb_narrow_M-1000_13TeV-madgraph.root
mv Histograms_MMR_RadionTohhTohbbhbb_narrow_M-1200_13TeV-madgraph.root Histograms_MMR_BulkGravTohhTohbbhbb_narrow_M-1200_13TeV-madgraph.root
cd ..
cd ..